# Use postgres/example user/password credentials
version: '3.1'

services:
  api:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_NAME: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbconfig:/docker-entrypoint-initdb.d/dbconfig
volumes:
  postgres_data:
    external: true
